version: '2'
services:
    jenkin-app:
        image: jenkin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=jenkin-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    jenkin-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: jenkin-cassandra
    jenkin-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=jenkin-cassandra
    jenkin-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: jenkin-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
